### ISSUE TITLE
All dimension binary indicators should read yes/no

### ISSUE THREAD

**Issue by ManuelCalavera** [seibelsbi/sbi#14]

**Comment by ManuelCalavera** [comment]
@jwmccartha Would you mind reviewing all dimensions to determine which fields are impacted by this issue? Post here and then assign to me for triage. Thanks

**Comment by jwmccartha** [comment]
@ManuelCalavera  I have reviewed all the dimension tables. The following fields are showing 1/0 instead of Yes/No:

Audit Tag in DimAudit table

Type of PayeeCode in DimCheckPayment table

Verified Phone, Verified Address and Verified Mortgage Co in DimClaim table

**Comment by randyvol** [comment]
So to recap... did you want me to fix FactPolicyCoverage or all the above plus FactPolicyCoverage?
What about IsDeleted/IsUpdated?

**Comment by ManuelCalavera** [comment]
Nope nope nope. This is only for those dimension attributes that end users filter on. In most cases we've addressed them but there are a few exceptions it seems.

AuditTag, IsDeleted/Updated, etc. are truly our properties and we need the bit flag for faster lookups in the ETL process.

**Comment by randyvol** [comment]
@jwmccartha: are these fixed yet?  If not, what is left to do?

**Comment by jwmccartha** [comment]
@randyvol  I just checked the fields mentioned in the Aug 27 post above and they have not been fixed on the database. The fields continue showing 1 and 0 in the dimension tables, when it should be Yes and No.

**Comment by ManuelCalavera** [comment]
@randyvol These should be the only ones per @jwmccartha 
```
Type of PayeeCode in DimCheckPayment table

Verified Phone, Verified Address and Verified Mortgage Co in DimClaim table
```

**Comment by jwmccartha** [comment]
@randyvol The below fields are currently showing a 1 or 0 in the dimension column on the DW database. Please change the 1s to Yes and the 0s to No. 

DimAudit table:
Audit Tag column

DimClaim table:
Verified Phone column
Verified Address column
Verified Mortgage Co column

FYI.....I re-verified Type of Payee Code in DimCheckPayment table. This field should NOT be addressed because its not an indicator field but capturing different types of payee.

**Comment by ManuelCalavera** [comment]
@jwmccartha per my earlier comment, please remove the audit tag. This one alongside indicators like IsDeleted/IsUpdated are more for our process.

**Comment by jwmccartha** [comment]
@ManuelCalavera  Sure I will update my post from this morning. I just thought you overlooked it since nothing was said about it. So that was why I included it.

**Comment by randyvol** [comment]
This is ON HOLD while I work on migration to Redshift
Will pick up first thing after finishing migration.

**Comment by mcjoy** [comment]
@ManuelCalavera , 4 fields are mentioned above.  Just to be clear, I am to review all dimensions (not just these 4)  and find the fields to change?

**Comment by ManuelCalavera** [comment]
@mcjoy I think @jwmccartha already did the analysis and since no new fields have been added the ones noted above should be sufficient.

**Comment by jwmccartha** [comment]
@mcjoy There are only 3 fields that needs this fix. 

The below fields are currently showing a 1 or 0 in the dimension column on the DW database. Please change the 1s to Yes and the 0s to No. Since these columns are capturing an indicator.

DimClaim table:
Verified Phone column
Verified Address column
Verified Mortgage Co column

**Comment by mcjoy** [comment]
Code pushed to Idea/RedshiftSupport branch
