### ISSUE TITLE
Request to add Coverages A - F as new measures in Pentaho.

### ISSUE THREAD

**Issue by jwmccartha** [seibelsbi/sbi#16]

**Comment by ManuelCalavera** [comment]
@marchise I've added Coverage A-D **limits**.

Do you per chance know if this one pertains to limits or premium? Also, if I get the logic for Coverages E-F I can complete this one.

**Comment by marchise** [comment]
@ManuelCalavera These measures should pertain to the limits.  Since we already have A-D, we just need to incorporate measures for coverages E & F as well.  

I'm assuming this is only for **Homeowners** and for customers **CSI**, **EPIC**, **GS**, **SJ** they all have the following for the aforementioned coverages (*please also see [CoveragesA-F.xlsx](https://github.com/seibelsbi/sbi/files/126653/CoveragesA-F.xlsx)*):

Coverage	| CoverageCode| CoverageDescription
--------------|--------------|--------------|
CoverageE|	PL|	Cov E - Personal Liability|
CoverageF|	MEDPM|	Cov F - Medical Payments|

**Comment by ManuelCalavera** [comment]
Fixed per commit above. Part of next load. Closing.
